### ISSUE TITLE
Issues and suggestions

### ISSUE THREAD

**Issue by Weiyeahh** [brianacampos/TermProject#1]
Goodthings: Very rich content and beautiful grid design! I really like the visuals! 

Technical suggestion:
1.for the about us div, the show less button doesn't work. consider add:
`type="button"`, in the button div, otherwise its default is submit
2.for the Featured Content image show room, the dots below the image doesn't work. 
dont use inline operator. consider replace the very long function plusSlides, showSlides with img.src=""
```
  <a class="prev" onclick="plusSlides(-1)">&gt;</a>
      <a class="next" onclick="plusSlides(1)">&lt;</a>
```

Content suggestion: 
1. Maybe can make the website more interactive, such as clicking or hovering on the image and a different image of the same place show up. 
2. for the outdoor section, another heading showed up and overlapped.

**Comment by brianacampos** [comment]
Thank you! I will definitely implement all the feedback you have provided!
