### ISSUE TITLE
Technical Issue 1: Javascript linked to text instead of button

### ISSUE THREAD

**Issue by asibole1** [brianacampos/TermProject#2]
Hi Briana, 
I love what you are doing with the "Who we are" section on the homepage, and I wanted to let you know that when you click the "more" it is working as intended, but when you click "less" nothing happens. You can see that the function is working when you click text content rather than the button:

https://github.com/brianacampos/TermProject/blob/64e89b94eb03dcc05d6fd552acab89f8bfb9a817/index.html#L284

Try copying the code from where you made the action of showing the content when you click the button rather than the text for a more intuitive user experience.

**Comment by brianacampos** [comment]
Thank you! I will definitely implement all the feedback you have provided!
