### ISSUE TITLE
Technical Issue 2: Feedback Form Overlaps Header - CSS Needed

### ISSUE THREAD

**Issue by asibole1** [brianacampos/TermProject#3]
Hi Briana, 

If you take a look below you'll find that the feedback form is overlapping with the header, making it so the user cannot fill the first two fields. I searched your CSS files and it seems you did not add CSS for the class you assigned here, "feedback-form":

https://github.com/brianacampos/TermProject/blob/64e89b94eb03dcc05d6fd552acab89f8bfb9a817/contact-us.html#L78

I'm guessing you just forgot to style this element and you can use similar styling to the other types throughout the website, but I wanted to bring your attention to this bug so that you'll be able to get feedback on your site!

**Comment by brianacampos** [comment]
Thank you! Yes, I was in a rush but I finally implemented better CSS to the form!
