### ISSUE TITLE
Content Issue 1: Suggest Replace or Crop Stretched Image

### ISSUE THREAD

**Issue by asibole1** [brianacampos/TermProject#4]
Hi Briana, 

Overall I LOVE the imagery on your site; you get a great sense of the vibe in the Bay Area. I would suggest you either crop or replace the image below that serves as the background for the "Restaurants" header:

https://github.com/brianacampos/TermProject/blob/64e89b94eb03dcc05d6fd552acab89f8bfb9a817/index.html#L125-L128

I am sure there are much yummier, more enticing restaurant images you can find to draw the user into exploring more! I do love the overlays with the images and button, though, so definitely suggest you keep that.

**Comment by brianacampos** [comment]
Thank you! I have changed the picture I have in the background!
