### ISSUE TITLE
Content Issue 2: Suggest Style Change Where Restaurants Overlaps with Logo

### ISSUE THREAD

**Issue by asibole1** [brianacampos/TermProject#5]
Hi Briana, 

First, I love the fading effect you have on your header in the "Restaurants" page. However, it makes it a bit difficult to read once it's faded. I'd suggest either moving it to another line or maybe changing the color to one with high contrast with your blue logo, like maybe black or red. 

Here's the CSS I'm referring to: 
https://github.com/brianacampos/TermProject/blob/64e89b94eb03dcc05d6fd552acab89f8bfb9a817/content.css#L72-L77

And here's the location in your header: 
https://github.com/brianacampos/TermProject/blob/64e89b94eb03dcc05d6fd552acab89f8bfb9a817/restaurants.html#L34 

Great work!

**Comment by brianacampos** [comment]
Thank you! I will definitely fix that!
